### ISSUE TITLE
Dependence on MonoidalCategories not satisfied

### ISSUE THREAD

**Issue by HereAround** [homalg-project/Bialgebroids#30]
Version 2019.02.26 depends on MonoidalCategories and requires the latter to be newer than 2019.01.16. However, the latest version of MonoidalCategories that I can find is from 2018.12.01. Hence, I cannot satisfy this dependence.

Even more, a few weeks ago the package MonoidalCategories was located at https://github.com/homalg-project/MonoidalCategories.git. Now, I cannot find the package anymore...

**Comment by heiderich** [comment]
> Version 2019.02.26 depends on MonoidalCategories

Which specific commit do you refer to? In the current master (bd9e5220d4af7f01fee7c84e066477a5926862e2) of https://github.com/homalg-project/Bialgebroids does not depend on MonoidalCategories. This dependency was introduced in https://github.com/mohamed-barakat/Bialgebroids/commit/f4edcdeabc2e02b2ac412377c90ba720a88f640c  . Are you by chance using https://github.com/mohamed-barakat/Bialgebroids/commit/be9a8bc5ecd7b1f0d20865bd09bc09cd4c95db56?

**Comment by HereAround** [comment]
Thanks. You are right. I was indeed using https://github.com/mohamed-barakat/Bialgebroids/commit/be9a8bc5ecd7b1f0d20865bd09bc09cd4c95db56.

That resolved - I now run into an unsatisfied dependency on QPA. I cloned from https://github.com/homalg-project/QPA2 (e846e09758155c6a4ee49b1bbd0873f68fef7c23), but run into:

QPA: PackageAvailabilityInfo: dependency 'complexesforcap' is not satisfied
QPA: PackageAvailabilityInfo: check of needed packages done
QPA: PackageAvailabilityInfo: version 1.29 does not fit (required: >= 2.0)
QPA: PackageAvailabilityInfo: no installed version fits

Is a newer version required?

**Comment by heiderich** [comment]
> That resolved - I now run into an unsatisfied dependency on QPA. I cloned from https://github.com/homalg-project/QPA2 (e846e09758155c6a4ee49b1bbd0873f68fef7c23), but run into:
> 
> QPA: PackageAvailabilityInfo: dependency 'complexesforcap' is not satisfied
> QPA: PackageAvailabilityInfo: check of needed packages done
> QPA: PackageAvailabilityInfo: version 1.29 does not fit (required: >= 2.0)
> QPA: PackageAvailabilityInfo: no installed version fits

This surprises me in view of

https://github.com/homalg-project/QPA2/blob/e846e09758155c6a4ee49b1bbd0873f68fef7c23/PackageInfo.g#L51

It should have this dependency:

[ "ComplexesForCAP", ">=2018.09.15" ]

**Comment by HereAround** [comment]
Thanks - this was likely my mistake. I could not load ComplexesForCAP since I did not have the package

https://github.com/oysteins/InfiniteLists

In consequence, the above complaint was shown, which I misinterpreted as dependency on QPA rather than ComplexesForCAP.

Now it is working again.
