### ISSUE TITLE
CapCategory of RelationsOfAlgebroid

### ISSUE THREAD

**Issue by heiderich** [homalg-project/Bialgebroids#43]
After 

```
LoadPackage( "Bialgebroid" );
q := RightQuiver( "q(u,v)[a:u->v,b:v->u]" );
Q := HomalgFieldOfRationals( );
Qq := PathAlgebra( Q, q );
A := Algebroid( Qq, [ Qq.a * Qq.b - Qq.u, Qq.b * Qq.a - Qq.v ] );
```

the output of

```
IsIdenticalObj( CapCategory( RelationsOfAlgebroid(A)[1] ), A );
```
is `false`.

@mohamed-barakat: Is this indented? I think it is not.

**Comment by mohamed-barakat** [comment]
Yes it is intended:
* `CapCategory( RelationsOfAlgebroid(A)[1] )` is the algebroid defined by the path algebra without relations, while
* `A`  is the algebroid defined by the path algebra with relations.

**Comment by heiderich** [comment]
Oh, yes of course. Thanks.
