### ISSUE TITLE
Opposite of an algebroid

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/Bialgebroids#61]
The installation method for `Opposite` is given by:

https://github.com/homalg-project/Bialgebroids/blob/c8f75b63aa8b8e3b0d49358ee7f48fb11aa09ce0/gap/Algebroids.gi#L2179-L2198

I think the name is misleading and the current method ignores the defining quiver algebra, and returns the algebroid defined by the path algebra of the opposite quiver; which might be of a different dimension or even not finite dimensional. It also overwrite the CAP methods for opposite categories.

I would suggest renaming the method and fixing the code to `algebroid -> Algebroid( OppositeAlgebra( UnderlyingQuiverAlgebra( algebroid ) ) )`.

If you agree, I could provide a PR to fix that.

**Comment by mohamed-barakat** [comment]
I agree.
